"""update user

Revision ID: 19b498b15cef
Revises: 1a531eb146e1
Create Date: 2022-08-12 12:04:41.062095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b498b15cef'
down_revision = '1a531eb146e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('projectId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], name='members_projectId_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='members_userId_fkey')
    )
    # ### end Alembic commands ###
