"""edit-sections

Revision ID: 3fb8131fe763
Revises: 94737d6b2384
Create Date: 2022-09-13 00:21:06.070359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fb8131fe763'
down_revision = '94737d6b2384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('sectionId', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tasks', 'sections', ['sectionId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'sectionId')
    # ### end Alembic commands ###
