"""membres table

Revision ID: 1a531eb146e1
Revises: fc487db05205
Create Date: 2022-08-03 10:24:31.554942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a531eb146e1'
down_revision = 'fc487db05205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('userId', sa.Integer(), nullable=False))
    op.drop_constraint('members_users_fkey', 'members', type_='foreignkey')
    op.create_foreign_key(None, 'members', 'users', ['userId'], ['id'])
    op.drop_column('members', 'users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('users', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'members', type_='foreignkey')
    op.create_foreign_key('members_users_fkey', 'members', 'users', ['users'], ['id'])
    op.drop_column('members', 'userId')
    # ### end Alembic commands ###
