"""section_table

Revision ID: 94737d6b2384
Revises: d189c955d584
Create Date: 2022-09-08 18:14:09.050905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94737d6b2384'
down_revision = 'd189c955d584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('projectId', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    # ### end Alembic commands ###
